@baseUrl = http://localhost:8080/api
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDMxMDczNzAsInVzZXJfaWQiOjF9.SP4nDUGolkvHWIPrNKOmc5341Kd8Lmc9i2M9s2LYCeI

### 管理员登录
POST {{baseUrl}}/admin/login
Content-Type: application/json

{
    "username": "xifan",
    "password": "zhi583379"
}

### 批量生成卡密
POST {{baseUrl}}/admin/licenses/batch
Content-Type: application/json
Authorization: {{token}}

{
    "count": 1,
    "expired_at": "2025-03-27T23:59:59Z"
}

### 获取卡密列表
GET {{baseUrl}}/admin/licenses
Authorization: {{token}}

### 删除卡密
DELETE {{baseUrl}}/admin/licenses/3
Authorization: {{token}}

### 验证卡密
POST {{baseUrl}}/verify
Content-Type: application/json

{
    "license_key": "17c96c0c-9621-4150-b445-d9485f96be9e",
    "machine_code": "optional-machine-code"
}


